-- Allow anonymous users (no Google account yet)
ALTER TABLE users ALTER COLUMN google_id DROP NOT NULL;
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;

-- Replace the implicit UNIQUE on google_id with a partial index (NULLs allowed)
-- The old constraint name is auto-generated by Supabase as "users_google_id_key"
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_google_id_key;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_google_id_not_null ON users (google_id) WHERE google_id IS NOT NULL;

-- Sync token: hashed (sha256) for storage, raw token held by CLI
ALTER TABLE users ADD COLUMN IF NOT EXISTS sync_token_hash text UNIQUE;

-- Machine ID: stored for reference, not used as primary identifier
ALTER TABLE users ADD COLUMN IF NOT EXISTS machine_id text;

-- Last active timestamp: for cleanup of abandoned anonymous profiles
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_active_at timestamptz DEFAULT now();

-- Indexes for lookups
CREATE INDEX IF NOT EXISTS idx_users_sync_token_hash ON users (sync_token_hash) WHERE sync_token_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_machine_id ON users (machine_id) WHERE machine_id IS NOT NULL;

-- IP-based rate limiting for anonymous user creation
CREATE TABLE IF NOT EXISTS anon_creation_limits (
  ip_address text PRIMARY KEY,
  count int NOT NULL DEFAULT 1,
  window_start timestamptz NOT NULL DEFAULT now()
);
